Text_BootUpPC:
	.string "{PLAYER} booted up the PC.$"

gText_WhichPCShouldBeAccessed::
	.string "you probably only came here for the box?$"

gText_AccessedSomeonesPC::
	.string "Accessed stRANGERS'S PC.$"

gText_StorageSystemOpened::
	.string "why did u open this opened.$"

gText_AccessedPlayersPC::
	.string "Accessed {PLAYER}'s PC.$"

gText_AccessedLanettesPC::
	.string "Accessed bill but a girl's PC.$"
